#!/usr/bin/env bash
# Pings the ip address passed as an argument
# Ping should repeat 5 times
# should display

if [ "$#" -eq 0 ]
then
  echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
  ping -c 5 "$1"
fi