#!/usr/bin/env bash
# echo "To infinity and beyond" indefinitely with
# with a 2 sec slleep in between each iteration.
#  The  echo "I am invincible!!!" between each iteration.

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "I am invincible!!!"' SIGTERM 
done