#!/usr/bin/env bash
# A bash script that Displays the contents
# of the file `/etc/passwd`.
# Your script should only display:
# username
# user id
# Home directory path for the user

while read -r passwd; do
  echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"