#!/usr/bin/env bash
# Parses Apache log files in list format.
# a Bash script that displays the visitor IP
# along with the HTTP status code from the Apache log file.
# Ordered from the greatest to the lowest number of occurrences

awk '{ print $1 " " $9}' apache-access.log | sort | uniq -c | sort -rn