#!/usr/bin/env bash
# This script is displaying "Best School" 9 times
# and best school on 9th Occurence then Hi

i=0

while ((i<10))
do
    if ((i==9))
    then
        echo "Hi"
    fi
    echo "Best School"
	((i++))
done